/* 本文件由 tools/gen_assets.py 生成，不要手改 */
#pragma once

typedef enum {
    ASSET_BG_INFO,
    ASSET_BG_LIST,
    ASSET_BG_MENU,
    ASSET_BG_PLAY_A,
    ASSET_BG_PLAY_B,
    ASSET_BG_PLAY_C,
    ASSET_BG_SPLASH,
    ASSET_BG_VOL,
    ASSET_HL_MENU,
    ASSET_HL_ROW,
    ASSET_IC_BT,
    ASSET_IC_NEXT,
    ASSET_IC_NOTE,
    ASSET_IC_PAUSE,
    ASSET_IC_PAUSE_BIG,
    ASSET_IC_PLAY,
    ASSET_IC_PLAY_BIG,
    ASSET_IC_PREV,
    ASSET_IC_STAR_OFF,
    ASSET_IC_STAR_ON,
    ASSET_IC_WIFI,
    ASSET_PLACEHOLDER_COVER,
    ASSET_PLACEHOLDER_COVER_72,
    ASSET_PLACEHOLDER_COVER_96,
    ASSET_FONT_CJK_12,
    ASSET_FONT_CJK_16,
    ASSET_INDEX,
    ASSET_PINYIN,
    ASSET_COUNT,
} asset_id_t;

/* 便于调试：id → 文件名 */
static const char *asset_names[] = {
    "bg_info.png",
    "bg_list.png",
    "bg_menu.png",
    "bg_play_a.png",
    "bg_play_b.png",
    "bg_play_c.png",
    "bg_splash.png",
    "bg_vol.png",
    "hl_menu.png",
    "hl_row.png",
    "ic_bt.png",
    "ic_next.png",
    "ic_note.png",
    "ic_pause.png",
    "ic_pause_big.png",
    "ic_play.png",
    "ic_play_big.png",
    "ic_prev.png",
    "ic_star_off.png",
    "ic_star_on.png",
    "ic_wifi.png",
    "placeholder_cover.png",
    "placeholder_cover_72.png",
    "placeholder_cover_96.png",
    "font_cjk_12.bin",
    "font_cjk_16.bin",
    "index.html.gz",
    "pinyin.bin",
};
